# Generated by Django 2.2.7 on 2019-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='demoboll',
            field=models.BooleanField(null=True),
        ),
    ]
