# Generated by Django 2.2.7 on 2019-11-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_accession_demoboll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbarium',
            name='photo',
            field=models.ImageField(upload_to='herbarium'),
        ),
        migrations.AlterField(
            model_name='plantphoto',
            name='photo',
            field=models.ImageField(upload_to='plantphoto'),
        ),
    ]
