# Generated by Django 2.2.7 on 2019-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20191112_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbarium',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='plantphoto',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
