# Generated by Django 3.0.3 on 2020-02-26 09:37

from django.db import migrations, models

def gen_flatfields(apps, schema_editor):
    
    Accession = apps.get_model('lims', 'Accession')
 
    queryset = Accession.objects.select_related('species', 'species__genome', 'species__genome__subgenus', 'species__genome__subgenus__genus').all()

    for accession in queryset.iterator():
        accession.speciesflat = accession.species.species
        accession.genomeflat = accession.species.genome.genome
        accession.subgenusflat = accession.species.genome.subgenus.subgenus
        accession.genusflat = accession.species.genome.subgenus.genus.genus
        accession.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20191113_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='genomeflat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accession',
            name='genusflat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accession',
            name='speciesflat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accession',
            name='subgenusflat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(gen_flatfields),
    ]
