# Generated by Django 3.0.3 on 2020-02-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20200226_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='species',
        ),
    ]
