# Generated by Django 3.0.3 on 2020-02-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_remove_accession_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='subgenus',
            name='genus',
        ),
        migrations.DeleteModel(
            name='Genome',
        ),
        migrations.DeleteModel(
            name='Genus',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='Subgenus',
        ),
    ]
