# Generated by Django 3.0.5 on 2020-04-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_auto_20200226_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='collection_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='file_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='file_names',
            field=models.TextField(blank=True),
        ),
    ]
