# Generated by Django 3.0.5 on 2020-04-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_auto_20200421_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedpacket',
            name='datecollected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
