# Generated by Django 2.1.3 on 2018-12-03 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('W', 'Wild'), ('D', 'Domesticated')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeedPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspringa', to='lims.Plant')),
                ('parentb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspringb', to='lims.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=200)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Genome')),
            ],
        ),
        migrations.CreateModel(
            name='SubGenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Genus')),
            ],
        ),
        migrations.AddField(
            model_name='seed',
            name='seed_packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.SeedPacket'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fromseed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Seed'),
        ),
        migrations.AddField(
            model_name='genome',
            name='subgenus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.SubGenus'),
        ),
        migrations.AddField(
            model_name='accession',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Species'),
        ),
    ]
