# Generated by Django 2.2.2 on 2019-06-24 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('W', 'Wild'), ('D', 'Domesticated'), ('L', 'Landrace'), ('U', 'Unknown')], max_length=1, null=True)),
                ('alternatenames', models.CharField(blank=True, max_length=100)),
                ('pinumber', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Genera',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('flowering', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('accession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Accession')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=200)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('grantnumber', models.TextField(blank=True)),
                ('grantagency', models.TextField(blank=True)),
                ('lead', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenus', models.CharField(blank=True, max_length=200)),
                ('genus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Genus')),
            ],
            options={
                'verbose_name_plural': 'SubGenera',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=200)),
                ('genome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Genome')),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='SeedPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
                ('datecollected', models.DateField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('checkedoutby', models.CharField(blank=True, max_length=20)),
                ('accession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Accession')),
                ('parenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offspringa', to='lims.Plant')),
                ('parentb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offspringb', to='lims.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('D', 'DNA'), ('R', 'RNA'), ('P', 'Protein'), ('E', 'Epigenetic'), ('O', 'Other')], max_length=1, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sequencingcompany', models.CharField(blank=True, max_length=30)),
                ('pcrfree', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('sranumber', models.CharField(blank=True, max_length=15)),
                ('coverage', models.CharField(blank=True, max_length=15)),
                ('strategy', models.CharField(blank=True, max_length=20)),
                ('trackingnumber', models.CharField(blank=True, max_length=100)),
                ('sequenceinstrument', models.CharField(blank=True, max_length=100)),
                ('accession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Accession')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='fromseed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Seed'),
        ),
        migrations.AddField(
            model_name='plant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Project'),
        ),
        migrations.AddField(
            model_name='plant',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Sample'),
        ),
        migrations.AddField(
            model_name='genome',
            name='subgenus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Subgenus'),
        ),
        migrations.AddField(
            model_name='accession',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Species'),
        ),
    ]
