# Generated by Django 2.1.4 on 2019-03-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedpacket',
            name='parenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offspringa', to='lims.Plant'),
        ),
        migrations.AlterField(
            model_name='seedpacket',
            name='parentb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offspringb', to='lims.Plant'),
        ),
    ]
