# Generated by Django 2.1.4 on 2019-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20190312_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project',
        ),
        migrations.AddField(
            model_name='plant',
            name='plant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seed',
            name='seed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seedpacket',
            name='seedpacket',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
