# Generated by Django 2.1.4 on 2019-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20190312_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projecturl',
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
