# Generated by Django 2.1.4 on 2019-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20190312_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
